# Generated by Django 5.2.7 on 2026-02-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_estimates/')),
                ('material_type', models.CharField(default='General Construction', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_cost_display', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
