# Generated by Django 5.2.7 on 2026-02-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('square_feet', models.IntegerField()),
                ('image', models.ImageField(upload_to='house_designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
