# Generated by Django 5.2.7 on 2026-02-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_housedesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='selected_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.housedesign'),
        ),
    ]
