# Generated by Django 5.2.7 on 2026-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buildingdetails_selected_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Toilet', 'Toilet'), ('Visiting Room', 'Visiting Room')], max_length=100),
        ),
    ]
