# Generated by Django 5.2.7 on 2026-02-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Toilet', 'Toilet'), ('Visiting Room', 'Visiting Room'), ('Living Room', 'Living Room'), ('Interior Paint', 'Interior Paint'), ('Exterior Paint', 'Exterior Paint')], max_length=100),
        ),
    ]
