# Generated by Django 5.2.7 on 2026-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='costestimationlog',
            name='floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='costestimationlog',
            name='square_footage',
            field=models.IntegerField(default=1000),
        ),
    ]
