# Generated by Django 5.2.7 on 2026-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_costestimationlog_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='total_area_sqft',
            field=models.IntegerField(default=1000, help_text='Total build-up area in square feet'),
        ),
    ]
